AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  object-detection-lambda

  Sample SAM Template for object-detection-lambda

Globals:
  Function:
    Runtime: python3.6
    Timeout: 3
    Environment:
      Variables:
        REGION: !Ref "AWS::Region"
    Tags:
      Project: "Logo Obfuscation"
      Course: "FastAi"

Resources:
  DetectObjectsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: app.lambda_handler
      Events:
        DetectObjects:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /detectobjects
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DetectObjectsFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/detectobjects/"
  DetectObjectsFunctionFunction:
    Description: "DetectObjectsFunction Lambda Function ARN"
    Value: !GetAtt DetectObjectsFunction.Arn
  DetectObjectsFunctionFunctionIamRole:
    Description: "Implicit IAM Role created for DetectObjectsFunction function"
    Value: !GetAtt DetectObjectsFunction.Arn
